### ISSUE TITLE
dconf -Warning

### ISSUE THREAD

**Issue by BrunoKlu** [jelle619/dragonos#5]
Hello !!,

At the end of the install, I have this lines displayed on the attached picture.

![IMG_3545](https://user-images.githubusercontent.com/73705824/97804095-eaa9fb00-1c4d-11eb-874a-e6463b5bdefd.jpg)

Sorry cannot copy paste the code as the laptop is rebooting after message...

Any help on this please?

Many thanks

**Comment by jelle619** [comment]
Thanks for trying out Dragon OS! Please try each of the following three commands and let me know if any if them give an error.

```bash
sed -i 's/managed=false/managed=true/g' /etc/NetworkManager/NetworkManager.conf
gsettings set org.gnome.desktop.wm.preferences button-layout ':minimize,maximize,close'
xdg-user-dirs-update
```


If they don't result in any errors, you can safely ignore the warning message.

**Comment by BrunoKlu** [comment]
Hi Jelle,
Thanks for your help,

Here is what I'm getting when running the commands,

`klu@debian:~$` sudo -s
[sudo] password for klu: 
root@debian:/home/klu# sed -i 's/managed=false/managed=true/g' /etc/NetworkManager/NetworkManager.conf
root@debian:/home/klu# gsettings set org.gnome.desktop.wm.preferences button-layout ':minimize,maximize,close'

(process:2474): dconf-WARNING **: 01:06:43.485: failed to commit changes to dconf: Error spawning command line “dbus-launch --autolaunch=6ab4b58fb7b84286b4ac8494c919dfbc --binary-syntax --close-stderr”: Child process exited with code 1
root@debian:/home/klu# xdg-user-dirs-update
`root@debian:/home/klu#`

**Comment by jelle619** [comment]
This is possibly related to #4. I will take another look at the script when I have some time. That warning is safe to ignore.

**Comment by jelle619** [comment]
As of the revised script, running on top of Debian 11, this warning is no longer shown.
